// Generated by CoffeeScript 2.6.1
(function() {
  var App;

  App = (function() {
    var div, shadow;

    class App extends HTMLElement {};

    shadow = App.attachShadow({
      mode: 'open'
    });

    div = document.createElement('div');

    div.textContent = "my div component";

    shadow.append(div);

    return App;

  }).call(this);

  customElements.define('my-app', App);

}).call(this);
